/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Inject } from "@nestjs/common";
import { Prisma, Annotation, AiModel, Image, User } from "@prisma/client";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { Logger } from "winston";
import { DbService } from "src/dbService/db.service";

export class AnnotationServiceBase {
  constructor(
    protected readonly prisma: DbService,
    @Inject("winston")
    protected readonly logger: Logger
  ) {}

  async count<T extends Prisma.AnnotationFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AnnotationFindManyArgs>
  ): Promise<number> {
    return await this.prisma.annotation.count(args);
  }

  async findMany<T extends Prisma.AnnotationFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AnnotationFindManyArgs>
  ): Promise<PaginatedInterface<Annotation>> {
    const [data, totalCount] = await Promise.all([
      this.prisma.annotation.findMany(args),
      this.prisma.annotation.count({ where: { deletedAt: null } }),
    ]);

    return { paginatedResult: data, totalCount };
  }
  async findOne<T extends Prisma.AnnotationFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.AnnotationFindUniqueArgs>
  ): Promise<Annotation | null> {
    return await this.prisma.annotation.findUnique(args);
  }
  async create<T extends Prisma.AnnotationCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AnnotationCreateArgs>
  ): Promise<Annotation> {
    return await this.prisma.annotation.create<T>(args);
  }
  async createMany<T extends Prisma.AnnotationCreateManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AnnotationCreateManyArgs>
  ): Promise<Prisma.BatchPayload> {
    return await this.prisma.annotation.createMany<T>(args);
  }
  async update<T extends Prisma.AnnotationUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AnnotationUpdateArgs>
  ): Promise<Annotation> {
    return await this.prisma.annotation.update<T>(args);
  }
  async delete<T extends Prisma.AnnotationDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.AnnotationDeleteArgs>
  ): Promise<Annotation> {
    return await this.prisma.annotation.delete(args);
  }

  async updateMany<T extends Prisma.AnnotationUpdateManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AnnotationUpdateManyArgs>
  ): Promise<Prisma.BatchPayload> {
    return await this.prisma.annotation.updateMany(args);
  }

  async getAimodel(parentId: string): Promise<AiModel | null> {
    return this.prisma.annotation
      .findUnique({
        where: { id: parentId },
      })
      .aimodel();
  }

  async getImage(parentId: string): Promise<Image | null> {
    return this.prisma.annotation
      .findUnique({
        where: { id: parentId },
      })
      .image();
  }

  async getValidatedBy(parentId: string): Promise<User | null> {
    return this.prisma.annotation
      .findUnique({
        where: { id: parentId },
      })
      .validatedBy();
  }
}
