/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";import { MockUserRoles } from "src/mockUserRole";import { AllowAllGuard } from "src/allowGuard";

import * as swagger from "@nestjs/swagger";
import { BatchPayload } from "../../BatchPayload";
import { Logger } from "winston";
import { fileDto } from "../../file.dto";
import * as XLSX from "xlsx";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { flattenObject } from "src/util/helpers";
import { ImageService } from "../image.service";
import { ImageCreateInput } from "./ImageCreateInput";
import { ImageCreateManyInput } from "./ImageCreateManyInput";
import { ImageWhereInput } from "./ImageWhereInput";
import { ImageWhereUniqueInput } from "./ImageWhereUniqueInput";
import { ImageFindManyArgs } from "./ImageFindManyArgs";
import { ImageupdateManyArgs } from "./ImageupdateManyArgs";
import { ImageUpdateInput } from "./ImageUpdateInput";
import { Image } from "./Image";
import { AnnotationWhereInput } from "../../annotation/base/AnnotationWhereInput";
import { Annotation } from "../../annotation/base/Annotation";
import { getListImageDto } from "./getListImage.dto";
@swagger.ApiBearerAuth()
export class ImageControllerBase {
  constructor(
    protected readonly service: ImageService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder,
    protected readonly logger: Logger
  ) {}

  @common.UseGuards(
    AllowAllGuard
  )
  @common.Post()
  @nestAccessControl.UseRoles({
    resource: "Image",
    action: "create",
    possession: "any",
  })
  @swagger.ApiCreatedResponse({ type: Image })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: ImageCreateInput,
    @MockUserRoles() userRoles: string[]
  ): Promise<Image> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Image",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      this.logger.log({
        level: "error",
        message: `providing the properties: ${properties} on ${"Image"} creation is forbidden for roles: ${roles}`,
      });

      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"Image"} creation is forbidden for roles: ${roles}`
      );
    }
    return await this.service.create({
      data: {
        ...data,

        project: {
          connect: data.project,
        },
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        deletedAt: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  // @common.UseGuards(
  //   defaultAuthGuard.DefaultAuthGuard,
  //   nestAccessControl.ACGuard
  // )
  // @common.Post("/createMany")
  // @nestAccessControl.UseRoles({
  //   resource: "Image",
  //   action: "create",
  //   possession: "any",
  // })
  // @swagger.ApiCreatedResponse({ type: Image })
  // @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  // async createMany(
  //   @common.Body() data: Array<ImageCreateManyInput>,
  //   @MockUserRoles() userRoles: string[]
  // ): Promise<BatchPayload | null> {
  //   const permission = this.rolesBuilder.permission({
  //     role: userRoles,
  //     action: "create",
  //     possession: "any",
  //     resource: "Image",
  //   });
  //   const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
  //   if (invalidAttributes.length) {
  //     const properties = invalidAttributes
  //       .map((attribute: string) => JSON.stringify(attribute))
  //       .join(", ");
  //     const roles = userRoles
  //       .map((role: string) => JSON.stringify(role))
  //       .join(",");
  //     this.logger.log({
  //       level: "error",
  //       message: `providing the properties: ${properties} on ${"Image"} creation is forbidden for roles: ${roles}`,
  //     });

  //     throw new errors.ForbiddenException(
  //       `providing the properties: ${properties} on ${"Image"} creation is forbidden for roles: ${roles}`
  //     );
  //   }
  //   return await this.service.createMany({
  //     data: data,
  //     skipDuplicates: false,
  //   });
  // }

  @common.UseGuards(
    AllowAllGuard
  )
  @common.Get()
  @nestAccessControl.UseRoles({
    resource: "Image",
    action: "read",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: getListImageDto })
  @swagger.ApiForbiddenResponse()
  @swagger.ApiQuery({
    type: () => ImageFindManyArgs,
    style: "deepObject",
    explode: true,
  })
  async findMany(
    @common.Req() request: Request,
    @MockUserRoles() userRoles: string[]
  ): Promise<PaginatedInterface<Image>> {
    const args = plainToClass(ImageFindManyArgs, request.query);

    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Image",
    });
    const results = await this.service.findMany({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        deletedAt: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },
      },
    });
    const result = results.paginatedResult.map((result: Image) =>
      permission.filter(result)
    );
    return { paginatedResult: result, totalCount: results.totalCount };
  }

  @common.UseGuards(
    AllowAllGuard
  )
  @common.Get("/fileExcel")
  @nestAccessControl.UseRoles({
    resource: "Image",
    action: "read",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: fileDto })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findDataForExcel(
    @MockUserRoles() userRoles: string[]
  ): Promise<fileDto> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Image",
    });
    const results = await this.service.findMany({
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        deletedAt: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },
      },
    });
    const result = results.paginatedResult.map((result: Image) =>
      permission.filter(result)
    );
    const flatResult = result.map((obj) => flattenObject(obj));
    var excelFile = XLSX.utils.json_to_sheet(flatResult);

    var Workbook = XLSX.utils.book_new();
    await XLSX.utils.book_append_sheet(Workbook, excelFile, "data");
    const file = await XLSX.write(Workbook, {
      bookType: "xlsx",
      bookSST: true,
      type: "base64",
    });
    return { file: file };
  }

  @common.UseGuards(
    AllowAllGuard
  )
  @common.Get("/:id")
  @nestAccessControl.UseRoles({
    resource: "Image",
    action: "read",
    possession: "own",
  })
  @swagger.ApiOkResponse({ type: Image })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ImageWhereUniqueInput,
    @MockUserRoles() userRoles: string[]
  ): Promise<Image | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Image",
    });
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        deletedAt: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      this.logger.log({
        level: "error",
        message: `No resource was found for ${JSON.stringify(params)}`,
      });
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return permission.filter(result);
  }

  @common.UseGuards(
    AllowAllGuard
  )
  @common.Patch("/:id")
  @nestAccessControl.UseRoles({
    resource: "Image",
    action: "update",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: Image })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ImageWhereUniqueInput,
    @common.Body()
    data: ImageUpdateInput,
    @MockUserRoles() userRoles: string[]
  ): Promise<Image | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Image",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      this.logger.log({
        level: "error",
        message: `No resource was found for ${JSON.stringify(params)}`,
      });
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"Image"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          project: {
            connect: data.project,
          },
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          deletedAt: true,
          name: true,

          project: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error: any) {
      if (isRecordNotFoundError(error)) {
        this.logger.log({
          level: "error",
          message: `No resource was found for ${JSON.stringify(params)}`,
        });
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseGuards(
    AllowAllGuard
  )
  @common.Delete("/:id")
  @nestAccessControl.UseRoles({
    resource: "Image",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: Image })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ImageWhereUniqueInput
  ): Promise<Image | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          deletedAt: true,
          name: true,

          project: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error: any) {
      if (isRecordNotFoundError(error)) {
        this.logger.log({
          level: "error",
          message: `No resource was found for ${JSON.stringify(params)}`,
        });
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseGuards(
    AllowAllGuard
  )
  @common.Get("/:id/annotations")
  @nestAccessControl.UseRoles({
    resource: "Image",
    action: "read",
    possession: "any",
  })
  @swagger.ApiQuery({
    type: () => AnnotationWhereInput,
    style: "deepObject",
    explode: true,
  })
  async findManyAnnotations(
    @common.Req() request: Request,
    @common.Param() params: ImageWhereUniqueInput,
    @MockUserRoles() userRoles: string[]
  ): Promise<Annotation[] | null> {
    const query: AnnotationWhereInput = request.query;
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Annotation",
    });
    const results = await this.service.findAnnotations(params.id, {
      where: query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        deletedAt: true,

        aimodel: {
          select: {
            id: true,
          },
        },

        image: {
          select: {
            id: true,
          },
        },

        validatedBy: {
          select: {
            id: true,
          },
        },
      },
    });
    return results && results.map((result) => permission.filter(result));
  }

  @common.UseGuards(
    AllowAllGuard
  )
  @common.Post("/:id/annotations")
  @nestAccessControl.UseRoles({
    resource: "Image",
    action: "update",
    possession: "any",
  })
  async createAnnotations(
    @common.Param() params: ImageWhereUniqueInput,
    @common.Body() body: ImageWhereUniqueInput[],
    @MockUserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      annotations: {
        connect: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Image",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"Image"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseGuards(
    AllowAllGuard
  )
  @common.Patch("/:id/annotations")
  @nestAccessControl.UseRoles({
    resource: "Image",
    action: "update",
    possession: "any",
  })
  async updateAnnotations(
    @common.Param() params: ImageWhereUniqueInput,
    @common.Body() body: ImageWhereUniqueInput[],
    @MockUserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      annotations: {
        set: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Image",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"Image"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseGuards(
    AllowAllGuard
  )
  @common.Delete("/:id/annotations")
  @nestAccessControl.UseRoles({
    resource: "Image",
    action: "update",
    possession: "any",
  })
  async deleteAnnotations(
    @common.Param() params: ImageWhereUniqueInput,
    @common.Body() body: ImageWhereUniqueInput[],
    @MockUserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      annotations: {
        disconnect: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Image",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"Image"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
