/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Inject } from "@nestjs/common";
import { Prisma, Image, Annotation, Project } from "@prisma/client";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { Logger } from "winston";
import { DbService } from "src/dbService/db.service";

export class ImageServiceBase {
  constructor(
    protected readonly prisma: DbService,
    @Inject("winston")
    protected readonly logger: Logger
  ) {}

  async count<T extends Prisma.ImageFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ImageFindManyArgs>
  ): Promise<number> {
    return await this.prisma.image.count(args);
  }

  async findMany<T extends Prisma.ImageFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ImageFindManyArgs>
  ): Promise<PaginatedInterface<Image>> {
    const [data, totalCount] = await Promise.all([
      this.prisma.image.findMany(args),
      this.prisma.image.count({ where: { deletedAt: null } }),
    ]);

    return { paginatedResult: data, totalCount };
  }
  async findOne<T extends Prisma.ImageFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ImageFindUniqueArgs>
  ): Promise<Image | null> {
    return await this.prisma.image.findUnique(args);
  }
  async create<T extends Prisma.ImageCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ImageCreateArgs>
  ): Promise<Image> {
    return await this.prisma.image.create<T>(args);
  }
  async createMany<T extends Prisma.ImageCreateManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ImageCreateManyArgs>
  ): Promise<Prisma.BatchPayload> {
    return await this.prisma.image.createMany<T>(args);
  }
  async update<T extends Prisma.ImageUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ImageUpdateArgs>
  ): Promise<Image> {
    return await this.prisma.image.update<T>(args);
  }
  async delete<T extends Prisma.ImageDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ImageDeleteArgs>
  ): Promise<Image> {
    return await this.prisma.image.delete(args);
  }

  async updateMany<T extends Prisma.ImageUpdateManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ImageUpdateManyArgs>
  ): Promise<Prisma.BatchPayload> {
    return await this.prisma.image.updateMany(args);
  }

  async findAnnotations(
    parentId: string,
    args: Prisma.AnnotationFindManyArgs
  ): Promise<Annotation[] | null> {
    return this.prisma.image
      .findUnique({
        where: { id: parentId },
      })
      .annotations(args);
  }

  async getProject(parentId: string): Promise<Project | null> {
    return this.prisma.image
      .findUnique({
        where: { id: parentId },
      })
      .project();
  }
}
