/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Inject } from "@nestjs/common";
import { Prisma, Project, Image, Collaborator, User } from "@prisma/client";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { Logger } from "winston";
import { DbService } from "src/dbService/db.service";

export class ProjectServiceBase {
  constructor(
    protected readonly prisma: DbService,
    @Inject("winston")
    protected readonly logger: Logger
  ) {}

  async count<T extends Prisma.ProjectFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProjectFindManyArgs>
  ): Promise<number> {
    return await this.prisma.project.count(args);
  }

  async findMany<T extends Prisma.ProjectFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProjectFindManyArgs>
  ): Promise<PaginatedInterface<Project>> {
    const [data, totalCount] = await Promise.all([
      this.prisma.project.findMany(args),
      this.prisma.project.count({ where: { deletedAt: null } }),
    ]);

    return { paginatedResult: data, totalCount };
  }
  async findOne<T extends Prisma.ProjectFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProjectFindUniqueArgs>
  ): Promise<Project | null> {
    return await this.prisma.project.findUnique(args);
  }
  async create<T extends Prisma.ProjectCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProjectCreateArgs>
  ): Promise<Project> {
    return await this.prisma.project.create<T>(args);
  }
  async createMany<T extends Prisma.ProjectCreateManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProjectCreateManyArgs>
  ): Promise<Prisma.BatchPayload> {
    return await this.prisma.project.createMany<T>(args);
  }
  async update<T extends Prisma.ProjectUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProjectUpdateArgs>
  ): Promise<Project> {
    return await this.prisma.project.update<T>(args);
  }
  async delete<T extends Prisma.ProjectDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProjectDeleteArgs>
  ): Promise<Project> {
    return await this.prisma.project.delete(args);
  }

  async updateMany<T extends Prisma.ProjectUpdateManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProjectUpdateManyArgs>
  ): Promise<Prisma.BatchPayload> {
    return await this.prisma.project.updateMany(args);
  }

  async findImages(
    parentId: string,
    args: Prisma.ImageFindManyArgs
  ): Promise<Image[] | null> {
    return this.prisma.project
      .findUnique({
        where: { id: parentId },
      })
      .images(args);
  }

  async findCollaborators(
    parentId: string,
    args: Prisma.CollaboratorFindManyArgs
  ): Promise<Collaborator[] | null> {
    return this.prisma.project
      .findUnique({
        where: { id: parentId },
      })
      .collaborators(args);
  }

  async getUser(parentId: string): Promise<User | null> {
    return this.prisma.project
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
