/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Inject } from "@nestjs/common";
import { Prisma, AiModel, Annotation } from "@prisma/client";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { Logger } from "winston";
import { DbService } from "src/dbService/db.service";

export class AiModelServiceBase {
  constructor(
    protected readonly prisma: DbService,
    @Inject("winston")
    protected readonly logger: Logger
  ) {}

  async count<T extends Prisma.AiModelFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AiModelFindManyArgs>
  ): Promise<number> {
    return await this.prisma.aiModel.count(args);
  }

  async findMany<T extends Prisma.AiModelFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AiModelFindManyArgs>
  ): Promise<PaginatedInterface<AiModel>> {
    const [data, totalCount] = await Promise.all([
      this.prisma.aiModel.findMany(args),
      this.prisma.aiModel.count({ where: { deletedAt: null } }),
    ]);

    return { paginatedResult: data, totalCount };
  }
  async findOne<T extends Prisma.AiModelFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.AiModelFindUniqueArgs>
  ): Promise<AiModel | null> {
    return await this.prisma.aiModel.findUnique(args);
  }
  async create<T extends Prisma.AiModelCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AiModelCreateArgs>
  ): Promise<AiModel> {
    return await this.prisma.aiModel.create<T>(args);
  }
  async createMany<T extends Prisma.AiModelCreateManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AiModelCreateManyArgs>
  ): Promise<Prisma.BatchPayload> {
    return await this.prisma.aiModel.createMany<T>(args);
  }
  async update<T extends Prisma.AiModelUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AiModelUpdateArgs>
  ): Promise<AiModel> {
    return await this.prisma.aiModel.update<T>(args);
  }
  async delete<T extends Prisma.AiModelDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.AiModelDeleteArgs>
  ): Promise<AiModel> {
    return await this.prisma.aiModel.delete(args);
  }

  async updateMany<T extends Prisma.AiModelUpdateManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AiModelUpdateManyArgs>
  ): Promise<Prisma.BatchPayload> {
    return await this.prisma.aiModel.updateMany(args);
  }

  async findAnnotations(
    parentId: string,
    args: Prisma.AnnotationFindManyArgs
  ): Promise<Annotation[] | null> {
    return this.prisma.aiModel
      .findUnique({
        where: { id: parentId },
      })
      .annotations(args);
  }
}
