/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Inject } from "@nestjs/common";
import { Prisma, Collaborator, User, Project } from "@prisma/client";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { Logger } from "winston";
import { DbService } from "src/dbService/db.service";

export class CollaboratorServiceBase {
  constructor(
    protected readonly prisma: DbService,
    @Inject("winston")
    protected readonly logger: Logger
  ) {}

  async count<T extends Prisma.CollaboratorFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CollaboratorFindManyArgs>
  ): Promise<number> {
    return await this.prisma.collaborator.count(args);
  }

  async findMany<T extends Prisma.CollaboratorFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CollaboratorFindManyArgs>
  ): Promise<PaginatedInterface<Collaborator>> {
    const [data, totalCount] = await Promise.all([
      this.prisma.collaborator.findMany(args),
      this.prisma.collaborator.count({ where: { deletedAt: null } }),
    ]);

    return { paginatedResult: data, totalCount };
  }
  async findOne<T extends Prisma.CollaboratorFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CollaboratorFindUniqueArgs>
  ): Promise<Collaborator | null> {
    return await this.prisma.collaborator.findUnique(args);
  }
  async create<T extends Prisma.CollaboratorCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CollaboratorCreateArgs>
  ): Promise<Collaborator> {
    return await this.prisma.collaborator.create<T>(args);
  }
  async createMany<T extends Prisma.CollaboratorCreateManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CollaboratorCreateManyArgs>
  ): Promise<Prisma.BatchPayload> {
    return await this.prisma.collaborator.createMany<T>(args);
  }
  async update<T extends Prisma.CollaboratorUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CollaboratorUpdateArgs>
  ): Promise<Collaborator> {
    return await this.prisma.collaborator.update<T>(args);
  }
  async delete<T extends Prisma.CollaboratorDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CollaboratorDeleteArgs>
  ): Promise<Collaborator> {
    return await this.prisma.collaborator.delete(args);
  }

  async updateMany<T extends Prisma.CollaboratorUpdateManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CollaboratorUpdateManyArgs>
  ): Promise<Prisma.BatchPayload> {
    return await this.prisma.collaborator.updateMany(args);
  }

  async getUser(parentId: string): Promise<User | null> {
    return this.prisma.collaborator
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }

  async getProject(parentId: string): Promise<Project | null> {
    return this.prisma.collaborator
      .findUnique({
        where: { id: parentId },
      })
      .project();
  }
}
