/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CollaboratorWhereInput } from "./CollaboratorWhereInput";
import { Type } from "class-transformer";
import { CollaboratorOrderByInput } from "./CollaboratorOrderByInput";

@ArgsType()
class CollaboratorFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => CollaboratorWhereInput,
  })
  @Field(() => CollaboratorWhereInput, { nullable: true })
  @Type(() => CollaboratorWhereInput)
  where?: CollaboratorWhereInput;

  @ApiProperty({
    required: false,
    type: CollaboratorOrderByInput,
  })
  @Field(() => CollaboratorOrderByInput, { nullable: true })
  @Type(() => CollaboratorOrderByInput)
  orderBy?: CollaboratorOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { CollaboratorFindManyArgs };
