/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";import { MockUserRoles } from "src/mockUserRole";import { AllowAllGuard } from "src/allowGuard";

import * as swagger from "@nestjs/swagger";
import { BatchPayload } from "../../BatchPayload";
import { Logger } from "winston";
import { fileDto } from "../../file.dto";
import * as XLSX from "xlsx";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { flattenObject } from "src/util/helpers";
import { CollaboratorService } from "../collaborator.service";
import { CollaboratorCreateInput } from "./CollaboratorCreateInput";
import { CollaboratorCreateManyInput } from "./CollaboratorCreateManyInput";
import { CollaboratorWhereInput } from "./CollaboratorWhereInput";
import { CollaboratorWhereUniqueInput } from "./CollaboratorWhereUniqueInput";
import { CollaboratorFindManyArgs } from "./CollaboratorFindManyArgs";
import { CollaboratorupdateManyArgs } from "./CollaboratorupdateManyArgs";
import { CollaboratorUpdateInput } from "./CollaboratorUpdateInput";
import { Collaborator } from "./Collaborator";
import { getListCollaboratorDto } from "./getListCollaborator.dto";
@swagger.ApiBearerAuth()
export class CollaboratorControllerBase {
  constructor(
    protected readonly service: CollaboratorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder,
    protected readonly logger: Logger
  ) {}

  @common.UseGuards(
    AllowAllGuard
  )
  @common.Post()
  @nestAccessControl.UseRoles({
    resource: "Collaborator",
    action: "create",
    possession: "any",
  })
  @swagger.ApiCreatedResponse({ type: Collaborator })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: CollaboratorCreateInput,
    @MockUserRoles() userRoles: string[]
  ): Promise<Collaborator> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Collaborator",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      this.logger.log({
        level: "error",
        message: `providing the properties: ${properties} on ${"Collaborator"} creation is forbidden for roles: ${roles}`,
      });

      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"Collaborator"} creation is forbidden for roles: ${roles}`
      );
    }
    return await this.service.create({
      data: {
        ...data,

        user: {
          connect: data.user,
        },

        project: {
          connect: data.project,
        },
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        deletedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        project: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  // @common.UseGuards(
  //   defaultAuthGuard.DefaultAuthGuard,
  //   nestAccessControl.ACGuard
  // )
  // @common.Post("/createMany")
  // @nestAccessControl.UseRoles({
  //   resource: "Collaborator",
  //   action: "create",
  //   possession: "any",
  // })
  // @swagger.ApiCreatedResponse({ type: Collaborator })
  // @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  // async createMany(
  //   @common.Body() data: Array<CollaboratorCreateManyInput>,
  //   @MockUserRoles() userRoles: string[]
  // ): Promise<BatchPayload | null> {
  //   const permission = this.rolesBuilder.permission({
  //     role: userRoles,
  //     action: "create",
  //     possession: "any",
  //     resource: "Collaborator",
  //   });
  //   const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
  //   if (invalidAttributes.length) {
  //     const properties = invalidAttributes
  //       .map((attribute: string) => JSON.stringify(attribute))
  //       .join(", ");
  //     const roles = userRoles
  //       .map((role: string) => JSON.stringify(role))
  //       .join(",");
  //     this.logger.log({
  //       level: "error",
  //       message: `providing the properties: ${properties} on ${"Collaborator"} creation is forbidden for roles: ${roles}`,
  //     });

  //     throw new errors.ForbiddenException(
  //       `providing the properties: ${properties} on ${"Collaborator"} creation is forbidden for roles: ${roles}`
  //     );
  //   }
  //   return await this.service.createMany({
  //     data: data,
  //     skipDuplicates: false,
  //   });
  // }

  @common.UseGuards(
    AllowAllGuard
  )
  @common.Get()
  @nestAccessControl.UseRoles({
    resource: "Collaborator",
    action: "read",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: getListCollaboratorDto })
  @swagger.ApiForbiddenResponse()
  @swagger.ApiQuery({
    type: () => CollaboratorFindManyArgs,
    style: "deepObject",
    explode: true,
  })
  async findMany(
    @common.Req() request: Request,
    @MockUserRoles() userRoles: string[]
  ): Promise<PaginatedInterface<Collaborator>> {
    const args = plainToClass(CollaboratorFindManyArgs, request.query);

    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Collaborator",
    });
    const results = await this.service.findMany({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        deletedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        project: {
          select: {
            id: true,
          },
        },
      },
    });
    const result = results.paginatedResult.map((result: Collaborator) =>
      permission.filter(result)
    );
    return { paginatedResult: result, totalCount: results.totalCount };
  }

  @common.UseGuards(
    AllowAllGuard
  )
  @common.Get("/fileExcel")
  @nestAccessControl.UseRoles({
    resource: "Collaborator",
    action: "read",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: fileDto })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findDataForExcel(
    @MockUserRoles() userRoles: string[]
  ): Promise<fileDto> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Collaborator",
    });
    const results = await this.service.findMany({
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        deletedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        project: {
          select: {
            id: true,
          },
        },
      },
    });
    const result = results.paginatedResult.map((result: Collaborator) =>
      permission.filter(result)
    );
    const flatResult = result.map((obj) => flattenObject(obj));
    var excelFile = XLSX.utils.json_to_sheet(flatResult);

    var Workbook = XLSX.utils.book_new();
    await XLSX.utils.book_append_sheet(Workbook, excelFile, "data");
    const file = await XLSX.write(Workbook, {
      bookType: "xlsx",
      bookSST: true,
      type: "base64",
    });
    return { file: file };
  }

  @common.UseGuards(
    AllowAllGuard
  )
  @common.Get("/:id")
  @nestAccessControl.UseRoles({
    resource: "Collaborator",
    action: "read",
    possession: "own",
  })
  @swagger.ApiOkResponse({ type: Collaborator })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: CollaboratorWhereUniqueInput,
    @MockUserRoles() userRoles: string[]
  ): Promise<Collaborator | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Collaborator",
    });
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        deletedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        project: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      this.logger.log({
        level: "error",
        message: `No resource was found for ${JSON.stringify(params)}`,
      });
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return permission.filter(result);
  }

  @common.UseGuards(
    AllowAllGuard
  )
  @common.Patch("/:id")
  @nestAccessControl.UseRoles({
    resource: "Collaborator",
    action: "update",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: Collaborator })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: CollaboratorWhereUniqueInput,
    @common.Body()
    data: CollaboratorUpdateInput,
    @MockUserRoles() userRoles: string[]
  ): Promise<Collaborator | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Collaborator",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      this.logger.log({
        level: "error",
        message: `No resource was found for ${JSON.stringify(params)}`,
      });
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"Collaborator"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          user: {
            connect: data.user,
          },

          project: {
            connect: data.project,
          },
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          deletedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          project: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error: any) {
      if (isRecordNotFoundError(error)) {
        this.logger.log({
          level: "error",
          message: `No resource was found for ${JSON.stringify(params)}`,
        });
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseGuards(
    AllowAllGuard
  )
  @common.Delete("/:id")
  @nestAccessControl.UseRoles({
    resource: "Collaborator",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: Collaborator })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: CollaboratorWhereUniqueInput
  ): Promise<Collaborator | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          deletedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          project: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error: any) {
      if (isRecordNotFoundError(error)) {
        this.logger.log({
          level: "error",
          message: `No resource was found for ${JSON.stringify(params)}`,
        });
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
